services:

  hyperspace-1:
    image: hyper-cli
    container_name: hyperspace-1
    ports:
      - "50052:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-2:
    image: hyper-cli
    container_name: hyperspace-2
    ports:
      - "50053:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-3:
    image: hyper-cli
    container_name: hyperspace-3
    ports:
      - "50054:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-4:
    image: hyper-cli
    container_name: hyperspace-4
    ports:
      - "50055:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-5:
    image: hyper-cli
    container_name: hyperspace-5
    ports:
      - "50056:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-6:
    image: hyper-cli
    container_name: hyperspace-6
    ports:
      - "50057:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-7:
    image: hyper-cli
    container_name: hyperspace-7
    ports:
      - "50058:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-8:
    image: hyper-cli
    container_name: hyperspace-8
    ports:
      - "50059:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-9:
    image: hyper-cli
    container_name: hyperspace-9
    ports:
      - "50060:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-10:
    image: hyper-cli
    container_name: hyperspace-10
    ports:
      - "50061:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-11:
    image: hyper-cli
    container_name: hyperspace-11
    ports:
      - "50062:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-12:
    image: hyper-cli
    container_name: hyperspace-12
    ports:
      - "50063:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-13:
    image: hyper-cli
    container_name: hyperspace-13
    ports:
      - "50064:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-14:
    image: hyper-cli
    container_name: hyperspace-14
    ports:
      - "50065:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-15:
    image: hyper-cli
    container_name: hyperspace-15
    ports:
      - "50066:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-16:
    image: hyper-cli
    container_name: hyperspace-16
    ports:
      - "50067:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-17:
    image: hyper-cli
    container_name: hyperspace-17
    ports:
      - "50068:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-18:
    image: hyper-cli
    container_name: hyperspace-18
    ports:
      - "50069:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-19:
    image: hyper-cli
    container_name: hyperspace-19
    ports:
      - "50070:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-20:
    image: hyper-cli
    container_name: hyperspace-20
    ports:
      - "50071:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-21:
    image: hyper-cli
    container_name: hyperspace-21
    ports:
      - "50072:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-22:
    image: hyper-cli
    container_name: hyperspace-22
    ports:
      - "50073:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-23:
    image: hyper-cli
    container_name: hyperspace-23
    ports:
      - "50074:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-24:
    image: hyper-cli
    container_name: hyperspace-24
    ports:
      - "50075:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-25:
    image: hyper-cli
    container_name: hyperspace-25
    ports:
      - "50076:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-26:
    image: hyper-cli
    container_name: hyperspace-26
    ports:
      - "50077:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-27:
    image: hyper-cli
    container_name: hyperspace-27
    ports:
      - "50078:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-28:
    image: hyper-cli
    container_name: hyperspace-28
    ports:
      - "50079:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-29:
    image: hyper-cli
    container_name: hyperspace-29
    ports:
      - "50080:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-30:
    image: hyper-cli
    container_name: hyperspace-30
    ports:
      - "50081:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-31:
    image: hyper-cli
    container_name: hyperspace-31
    ports:
      - "50082:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-32:
    image: hyper-cli
    container_name: hyperspace-32
    ports:
      - "50083:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-33:
    image: hyper-cli
    container_name: hyperspace-33
    ports:
      - "50084:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-34:
    image: hyper-cli
    container_name: hyperspace-34
    ports:
      - "50085:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-35:
    image: hyper-cli
    container_name: hyperspace-35
    ports:
      - "50086:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-36:
    image: hyper-cli
    container_name: hyperspace-36
    ports:
      - "50087:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-37:
    image: hyper-cli
    container_name: hyperspace-37
    ports:
      - "50088:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-38:
    image: hyper-cli
    container_name: hyperspace-38
    ports:
      - "50089:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-39:
    image: hyper-cli
    container_name: hyperspace-39
    ports:
      - "50090:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-40:
    image: hyper-cli
    container_name: hyperspace-40
    ports:
      - "50091:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-41:
    image: hyper-cli
    container_name: hyperspace-41
    ports:
      - "50092:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-42:
    image: hyper-cli
    container_name: hyperspace-42
    ports:
      - "50093:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-43:
    image: hyper-cli
    container_name: hyperspace-43
    ports:
      - "50094:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-44:
    image: hyper-cli
    container_name: hyperspace-44
    ports:
      - "50095:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-45:
    image: hyper-cli
    container_name: hyperspace-45
    ports:
      - "50096:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-46:
    image: hyper-cli
    container_name: hyperspace-46
    ports:
      - "50097:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-47:
    image: hyper-cli
    container_name: hyperspace-47
    ports:
      - "50098:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-48:
    image: hyper-cli
    container_name: hyperspace-48
    ports:
      - "50099:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro

  hyperspace-49:
    image: hyper-cli
    container_name: hyperspace-49
    ports:
      - "50100:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro
