services:
  hyperspace-1:
    image: hyper-cli
    container_name: hyperspace-1
    ports:
      - "50051:50051"  # 映射守护进程端口
    environment:
      - AIOS_KEY=your_aios_key_here  # 替换为您的 AIOS_KEY
    restart: always
    command: /root/start-hyperspace.sh

  hyperspace-2:
    image: hyper-cli
    container_name: hyperspace-2
    ports:
      - "50052:50051"  # 映射守护进程端口
    environment:
      - AIOS_KEY=your_aios_key_here  # 替换为您的 AIOS_KEY
    restart: always
    command: /root/start-hyperspace.sh

  # 可以按照相同格式添加更多服务实例
  # 每个实例使用不同的端口映射
  # hyperspace-3:
  #   image: hyper-cli
  #   container_name: hyperspace-3
  #   ports:
  #     - "50053:50051"
  #   environment:
  #     - AIOS_KEY=your_aios_key_here
  #   restart: always
  #   command: /root/start-hyperspace.sh 