services:

  hyperspace-1:
    image: hyper-cli
    container_name: hyperspace-1
    ports:
      - "50052:50051"
    restart: always
    command: /root/start-hyperspace.sh
    volumes:
      - /root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:/root/.cache/hyperspace/models/hf__TheBloke___phi-2-GGUF__phi-2.Q4_K_M.gguf:ro
